name: front-test

on:
  pull_request:
    branches: [main]

jobs:
  front-test:
    runs-on: docker
    container:
      image: flutter-ci:stable
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - run: flutter pub get
      - run: dart pub global activate melos
      - run: melos analyze
      - run: melos test
