//! Routes stérilisation, prescriptions, modèles de prescription/CR.
//! Extrait de `lib.rs::build_router` (refactor taille).

use axum::{routing::get, Router};

use crate::{
    ccam_stock_mappings, consent_templates, cr_templates, lab_work_orders, medication_references,
    prescription_renew, prescription_send, prescription_templates, prescriptions, sterilization,
    sterilization_labels, stock_import, stock_items, stock_locations, AppState,
};

pub fn add(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/v1/cabinet/sterilization-cycles",
            get(sterilization::list_sterilization_cycles)
                .post(sterilization::create_sterilization_cycle),
        )
        .route(
            "/v1/cabinet/sterilization-cycles/:id/pouches",
            get(sterilization::list_sterilized_pouches).post(sterilization::add_sterilized_pouch),
        )
        .route(
            "/v1/sterilization/cycles/:id/labels.pdf",
            get(sterilization_labels::sterilization_cycle_labels_pdf),
        )
        .route(
            "/v1/sterilization/pouches/:code/use",
            axum::routing::post(sterilization_labels::use_sterilized_pouch),
        )
        .route(
            "/v1/cabinet/stock-items",
            get(stock_items::list_stock_items).post(stock_items::create_stock_item),
        )
        .route(
            "/v1/cabinet/stock-items/:id/movements",
            get(stock_items::list_stock_movements).post(stock_items::add_stock_movement),
        )
        .route(
            "/v1/cabinet/ccam-stock-mappings",
            get(ccam_stock_mappings::list_ccam_stock_mappings)
                .post(ccam_stock_mappings::create_ccam_stock_mapping),
        )
        .route(
            "/v1/cabinet/ccam-stock-mappings/:id",
            axum::routing::delete(ccam_stock_mappings::delete_ccam_stock_mapping),
        )
        .route(
            "/v1/cabinet/stock-locations",
            get(stock_locations::list_stock_locations).post(stock_locations::create_stock_location),
        )
        .route(
            "/v1/cabinet/stock-locations/:id",
            axum::routing::delete(stock_locations::delete_stock_location),
        )
        .route(
            "/v1/cabinet/stock-items/:id/locations",
            get(stock_locations::list_item_locations),
        )
        .route(
            "/v1/cabinet/stock-items/:id/locations/:location_id",
            axum::routing::patch(stock_locations::set_item_location_threshold),
        )
        .route(
            "/v1/cabinet/stock-items/:id/transfer",
            axum::routing::post(stock_locations::transfer_stock),
        )
        .route(
            "/v1/stock/import",
            axum::routing::post(stock_import::import_stock_csv),
        )
        .route(
            "/v1/medication-references",
            get(medication_references::search_medication_references),
        )
        .route(
            "/v1/cabinet/prescriptions",
            axum::routing::post(prescriptions::create_prescription),
        )
        .route(
            "/v1/cabinet/prescriptions/:id",
            get(prescriptions::get_prescription),
        )
        .route(
            "/v1/cabinet/prescriptions/:id/sign",
            axum::routing::post(prescriptions::sign_prescription),
        )
        .route(
            "/v1/cabinet/prescriptions/:id/send",
            axum::routing::post(prescription_send::send_prescription),
        )
        .route(
            "/v1/cabinet/prescriptions/:id/renew",
            axum::routing::post(prescription_renew::renew_prescription),
        )
        .route(
            "/v1/cabinet/prescriptions/:id/apply-template",
            axum::routing::post(prescription_templates::apply_prescription_template),
        )
        .route(
            "/v1/cabinet/prescription-templates",
            get(prescription_templates::list_prescription_templates)
                .post(prescription_templates::create_prescription_template),
        )
        .route(
            "/v1/cabinet/cr-templates",
            get(cr_templates::list_cr_templates).post(cr_templates::create_cr_template),
        )
        .route(
            "/v1/cabinet/cr-templates/:id",
            axum::routing::patch(cr_templates::patch_cr_template)
                .delete(cr_templates::delete_cr_template),
        )
        .route(
            "/v1/cabinet/consent-templates",
            get(consent_templates::list_consent_templates)
                .post(consent_templates::create_consent_template),
        )
        .route(
            "/v1/cabinet/consent-templates/:id",
            axum::routing::patch(consent_templates::patch_consent_template),
        )
        .route(
            "/v1/consent-templates/:id/render",
            axum::routing::post(consent_templates::render_consent_template),
        )
        .route(
            "/v1/cabinet/lab-work-orders",
            get(lab_work_orders::list_lab_work_orders).post(lab_work_orders::create_lab_work_order),
        )
        .route(
            "/v1/cabinet/lab-work-orders/today",
            get(lab_work_orders::list_today_lab_work_orders),
        )
        .route(
            "/v1/cabinet/lab-work-orders/:id",
            axum::routing::patch(lab_work_orders::patch_lab_work_order),
        )
}
