//! Routes pharmacie (commandes click-and-collect, réappro, devis pharmacie,
//! messagerie pharmacie). Extrait de `lib.rs::build_router` (refactor taille).

use axum::{routing::get, Router};

use crate::{pharmacy, prescriptions, AppState};

pub fn add(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/v1/cabinet/patients/:id/pharmacy",
            get(pharmacy::orders::get_cabinet_patient_pharmacy),
        )
        .route(
            "/v1/pharmacy/orders",
            get(pharmacy::orders::list_pharmacy_orders),
        )
        .route(
            "/v1/pharmacy/orders/:id",
            get(pharmacy::orders::get_pharmacy_order),
        )
        .route(
            "/v1/pharmacy/orders/:id/document",
            get(pharmacy::orders::get_pharmacy_order_document),
        )
        .route(
            "/v1/pharmacy/orders/:id/items",
            get(pharmacy::orders::get_pharmacy_order_items),
        )
        .route(
            "/v1/pharmacy/orders/:id/accept",
            axum::routing::post(pharmacy::orders::accept_pharmacy_order),
        )
        .route(
            "/v1/pharmacy/orders/:id/ready",
            axum::routing::post(pharmacy::orders::ready_pharmacy_order),
        )
        .route(
            "/v1/pharmacy/orders/:id/reject",
            axum::routing::post(pharmacy::orders::reject_pharmacy_order),
        )
        .route(
            "/v1/pharmacy/orders/pickup-scan",
            axum::routing::post(pharmacy::orders::pickup_scan),
        )
        .route(
            "/v1/cabinet/stock-requests",
            get(pharmacy::stock::list_cabinet_stock_requests)
                .post(pharmacy::stock::create_stock_request),
        )
        .route(
            "/v1/cabinet/stock-requests/:id/cancel",
            axum::routing::post(pharmacy::stock::cancel_stock_request),
        )
        .route(
            "/v1/pharmacy/stock-requests",
            get(pharmacy::stock::list_pharmacy_stock_requests),
        )
        .route(
            "/v1/pharmacy/quotes",
            get(pharmacy::quotes::list_pharmacy_quotes)
                .post(pharmacy::quotes::create_pharmacy_quote),
        )
        .route(
            "/v1/pharmacy/quotes/:id/send",
            axum::routing::post(pharmacy::quotes::send_pharmacy_quote),
        )
        .route(
            "/v1/account/pharmacy-quotes",
            get(pharmacy::quotes::list_account_pharmacy_quotes),
        )
        .route(
            "/v1/account/pharmacy-quotes/:id/accept",
            axum::routing::post(pharmacy::quotes::accept_pharmacy_quote),
        )
        .route(
            "/v1/account/pharmacy-quotes/:id/refuse",
            axum::routing::post(pharmacy::quotes::refuse_pharmacy_quote),
        )
        .route(
            "/v1/pharmacy/conversations",
            get(pharmacy::messaging::list_pharmacy_conversations),
        )
        .route(
            "/v1/pharmacy/conversations/:id/messages",
            get(pharmacy::messaging::get_pharmacy_conversation_messages)
                .post(pharmacy::messaging::send_pharmacy_message),
        )
        .route(
            "/v1/pharmacy/conversations/:id/read",
            axum::routing::post(pharmacy::messaging::mark_pharmacy_conversation_read),
        )
        .route(
            "/v1/pharmacy/stock-requests/:id/accept",
            axum::routing::post(pharmacy::stock::accept_stock_request),
        )
        .route(
            "/v1/pharmacy/stock-requests/:id/reject",
            axum::routing::post(pharmacy::stock::reject_stock_request),
        )
        .route(
            "/v1/pharmacy/stock-requests/:id/fulfill",
            axum::routing::post(pharmacy::stock::fulfill_stock_request),
        )
        .route(
            "/v1/account/prescriptions",
            get(prescriptions::list_account_prescriptions),
        )
        .route(
            "/v1/account/prescriptions/:id/order",
            axum::routing::post(pharmacy::orders::create_account_order),
        )
        .route(
            "/v1/account/orders",
            get(pharmacy::orders::list_account_orders),
        )
        .route(
            "/v1/account/orders/:id",
            get(pharmacy::orders::get_account_order),
        )
        .route(
            "/v1/account/orders/:id/cancel",
            axum::routing::post(pharmacy::orders::cancel_account_order),
        )
        .route(
            "/v1/account/orders/:id/pickup-token",
            get(pharmacy::orders::get_pickup_token),
        )
        .route(
            "/v1/account/pharmacy",
            get(pharmacy::orders::get_account_pharmacy).put(pharmacy::orders::put_account_pharmacy),
        )
}
